---
site_name: Strawberry Django
site_description: Strawberry integration with Django.
site_author: community
repo_name: strawberry-django
repo_url: https://github.com/strawberry-graphql/strawberry-django
edit_uri: edit/main/docs/
dev_addr: 127.0.0.1:7000

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: red
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: slate
      primary: green
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - content.code.annotate
    - navigation.instant

markdown_extensions:
  - tables
  - admonition
  - codehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - mkdocstrings:
  - search
  - minify:
      minify_html: true
  - markdownextradata:
      data: docs/data

nav:
  - index.md
  - quick-start.md
  - Guide:
      - guide/views.md
      - guide/types.md
      - guide/fields.md
      - guide/resolvers.md
      - guide/filters.md
      - guide/ordering.md
      - guide/pagination.md
      - guide/optimizer.md
      - guide/queries.md
      - guide/mutations.md
      - guide/subscriptions.md
      - guide/permissions.md
      - guide/relay.md
      - guide/authentication.md
      - guide/settings.md
      - guide/unit-testing.md
      - guide/export-schema.md
  - Integrations:
      - integrations/debug-toolbar.md
      - integrations/guardian.md
      - integrations/channels.md
      - integrations/choices-field.md
  - community-projects.md
  - contributing.md
  - FAQ: faq.md
