name: ðŸš€ AutoPub Release
concurrency: release

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write

jobs:
  check-release:
    name: ðŸ“¦ Check for release
    runs-on: ubuntu-latest
    outputs:
      has_release: ${{ steps.check.outputs['has-release'] }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Check for release
        id: check
        uses: autopub/autopub-action@v1
        with:
          command: check
          github-token: ${{ secrets.BOT_TOKEN }}

      - name: Debug info
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "has_release: ${{ steps.check.outputs['has-release'] }}"

  publish:
    name: ðŸ“¦ Publish to PyPI
    needs: check-release
    if: ${{ github.ref == 'refs/heads/main' && needs.check-release.outputs.has_release == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Debug info
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "has_release: ${{ needs.check-release.outputs.has_release }}"

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Prepare release
        uses: autopub/autopub-action@v1
        with:
          command: prepare

      - name: Build package
        uses: autopub/autopub-action@v1
        with:
          command: build

      - name: Publish to PyPI
        uses: autopub/autopub-action@v1
        with:
          command: publish
          github-token: ${{ secrets.BOT_TOKEN }}
          git-username: botberry
          git-email: bot@strawberry.rocks
